"""episodes and posting slots

Revision ID: 0b3932f1c2a9
Revises:
Create Date: 2026-09-08 21:26:07.936182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b3932f1c2a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episodes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("publish_on", sa.Date(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episodes")),
    )
    op.create_table(
        "posting_slots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.Column("episode_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posting_slots")),
        sa.UniqueConstraint("slot_date", name="uq_posting_slots_slot_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posting_slots")
    op.drop_table("episodes")
    # ### end Alembic commands ###
