"""workflow

Revision ID: b6ea0df80e57
Revises:
Create Date: 2026-09-09 00:33:28.400117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6ea0df80e57"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episodes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("publish_on", sa.Date(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episodes")),
    )
    op.create_index(op.f("ix_episodes_stage"), "episodes", ["stage"], unique=False)
    op.create_table(
        "plan_steps",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("episode_id", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_steps")),
    )
    op.create_index(
        op.f("ix_plan_steps_episode_id"), "plan_steps", ["episode_id"], unique=False
    )
    op.create_table(
        "posting_slots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.Column("episode_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posting_slots")),
        sa.UniqueConstraint("slot_date", name="uq_posting_slots_slot_date"),
    )
    op.create_table(
        "stage_transitions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("episode_id", sa.String(length=32), nullable=False),
        sa.Column("from_stage", sa.String(length=32), nullable=False),
        sa.Column("to_stage", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("happened_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_transitions")),
    )
    op.create_index(
        op.f("ix_stage_transitions_episode_id"),
        "stage_transitions",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stage_transitions_happened_at"),
        "stage_transitions",
        ["happened_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stage_transitions_happened_at"), table_name="stage_transitions"
    )
    op.drop_index(
        op.f("ix_stage_transitions_episode_id"), table_name="stage_transitions"
    )
    op.drop_table("stage_transitions")
    op.drop_table("posting_slots")
    op.drop_index(op.f("ix_plan_steps_episode_id"), table_name="plan_steps")
    op.drop_table("plan_steps")
    op.drop_index(op.f("ix_episodes_stage"), table_name="episodes")
    op.drop_table("episodes")
    # ### end Alembic commands ###
