"""create core workflow tables

Revision ID: f65eb45d4871
Revises: 
Create Date: 2026-09-05 22:55:01.866495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65eb45d4871'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('publish_on', sa.Date(), nullable=False),
    sa.Column('stage', sa.Enum('REGISTERED', 'MIXING', 'PLAN_READY', 'EDITING', 'REVIEW', 'PUBLISHED', name='stage'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_episodes_publish_on'), 'episodes', ['publish_on'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'kind', 'checksum'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_audio_files_checksum'), 'audio_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_audio_files_episode_id'), 'audio_files', ['episode_id'], unique=False)
    op.create_table('plan_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('completed_by', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'position')
    )
    op.create_index(op.f('ix_plan_steps_episode_id'), 'plan_steps', ['episode_id'], unique=False)
    op.create_table('stage_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('from_stage', sa.Enum('REGISTERED', 'MIXING', 'PLAN_READY', 'EDITING', 'REVIEW', 'PUBLISHED', name='stage'), nullable=False),
    sa.Column('to_stage', sa.Enum('REGISTERED', 'MIXING', 'PLAN_READY', 'EDITING', 'REVIEW', 'PUBLISHED', name='stage'), nullable=False),
    sa.Column('actor', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transitions_episode_id'), 'stage_transitions', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_transitions_episode_id'), table_name='stage_transitions')
    op.drop_table('stage_transitions')
    op.drop_index(op.f('ix_plan_steps_episode_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_audio_files_episode_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_checksum'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_episodes_publish_on'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
